name: Linux.do Auto Checkin

on:
  schedule:
    - cron: '0 1 * * *'  # 每天北京时间 9:00 运行
  workflow_dispatch:      # 支持手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        pip install -r requirements.txt
        playwright install firefox
    
    - name: Run checkin script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python linuxdo.py
